a:5:{i:0;s:100:"SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
";i:1;s:1601:"#0 C:\xampp\htdocs\magento_test\lib\Zend\Db\Adapter\Pdo\Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 C:\xampp\htdocs\magento_test\lib\Varien\Db\Adapter\Pdo\Mysql.php(320): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 C:\xampp\htdocs\magento_test\lib\Zend\Db\Adapter\Abstract.php(459): Varien_Db_Adapter_Pdo_Mysql->_connect()
#3 C:\xampp\htdocs\magento_test\lib\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#4 C:\xampp\htdocs\magento_test\lib\Varien\Db\Adapter\Pdo\Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#5 C:\xampp\htdocs\magento_test\app\code\core\Mage\Core\Model\Resource.php(169): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#6 C:\xampp\htdocs\magento_test\app\code\core\Mage\Core\Model\Resource.php(110): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Object(Mage_Core_Model_Config_Element))
#7 C:\xampp\htdocs\magento_test\app\code\core\Mage\Core\Model\Resource\Setup.php(141): Mage_Core_Model_Resource->getConnection('core_setup')
#8 C:\xampp\htdocs\magento_test\app\code\core\Mage\Core\Model\Resource\Setup.php(234): Mage_Core_Model_Resource_Setup->__construct('core_setup')
#9 C:\xampp\htdocs\magento_test\app\code\core\Mage\Core\Model\App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#10 C:\xampp\htdocs\magento_test\app\code\core\Mage\Core\Model\App.php(343): Mage_Core_Model_App->_initModules()
#11 C:\xampp\htdocs\magento_test\app\Mage.php(683): Mage_Core_Model_App->run(Array)
#12 C:\xampp\htdocs\magento_test\index.php(87): Mage::run('', 'store')
#13 {main}";s:3:"url";s:14:"/magento_test/";s:11:"script_name";s:23:"/magento_test/index.php";s:4:"skin";s:7:"default";}